export default {
  colors: {
    background: '#F0F0F7',
    primaryLighter: '#9871F5',
    primaryLight: '#916BEA',
    primary: '#8257E5',
    primaryDark: '#774DD6',
    primaryDarker: '#6842C2',
    secondary: '#04D361',
    secondaryDark: '#04BF58',
    titleInPrimary: '#FFFFFF',
    textInPrimary: '#D4C2FF',
    textTitle: '#32264D',
    textComplement: '#9C98A6',
    textBase: '#6A6180',
    lineInWhite: '#E6E6F0',
    inputBackground: '#F8F8FC',
    inputPlaceholder: '#C1BCCC',
    buttonText: '#FFFFFF',
    buttonNotAvailable: '#DCDCE5',
    boxBase: '#FFFFFF',
    boxFooter: '#FAFAFC',
    error: '#e33d3d',
  },
} as const;
