export { ReactComponent as CheckIcon } from './check.svg';
export { ReactComponent as PurpleHeartIcon } from './purple-heart.svg';
export { ReactComponent as BackIcon } from './back.svg';
export { ReactComponent as SuccessCheckIcon } from './success-check-icon.svg';
export { ReactComponent as SignOutIcon } from './signout.svg';
export { ReactComponent as StudyIcon } from './study.svg';
export { ReactComponent as GiveClassesIcon } from './give-classes.svg';
export { ReactComponent as WarningIcon } from './warning.svg';
export { ReactComponent as RocketIcon } from './rocket.svg';
